import { NgModule } from '@angular/core';
import {
  MatDialogModule,
  MatTabsModule,
  MatSidenavModule,
  MatFormFieldModule,
  MatInputModule,
  MatSelectModule,
  MatCheckboxModule,
  MatListModule,
  MatCardModule,
  MatButtonModule,
  MatStepperModule,
  MatTableModule,
  MatExpansionModule,
  MatGridListModule,
  MatTooltipModule,
} from '@angular/material';

@NgModule({
  imports: [
    MatDialogModule,
    MatTabsModule,
    MatSidenavModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatCheckboxModule,
    MatListModule,
    MatCardModule,
    MatButtonModule,
    MatStepperModule,
    MatTableModule,
    MatExpansionModule,
    MatGridListModule,
    MatTooltipModule,
  ],
  exports: [
    MatDialogModule,
    MatTabsModule,
    MatSidenavModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatCheckboxModule,
    MatListModule,
    MatCardModule,
    MatButtonModule,
    MatStepperModule,
    MatTableModule,
    MatExpansionModule,
    MatGridListModule,
    MatTooltipModule,
  ],
})
export class MaterialModule {}
