#! /bin/sh
echo "Running pre-push git hook."
echo "Installing dependencies..."
bash scripts/install-deps
echo "Running linters..."
bash scripts/check-code
echo "Running tests..."
echo "Not implemented."
echo "Done."
